#!/bin/bash
#
# Prepare anath demo environment and get anath admin password.
# Existing anath demo data are deleted.

set -eu

source scripts/shlib

if [ ! -d docker-compose ]
then
	virtualenv docker-compose
fi

set +u
source docker-compose/bin/activate
set -u
pip install docker-compose

output "Stop Anath Demo"
docker-compose --project-name demo -f docker-compose.yml down || true

output "Remove docker images"
docker rm demo_client_1 demo_openvpn_1 || true
docker rmi nginx openvpn || true

output "Remove existing databases"
docker rm demo_userdb_1 demo_pkidb_1 || true
docker volume rm demo_pkidb demo_userdb || true

output "Start Anath Demo"
docker-compose --project-name demo -f docker-compose.yml up -d

output "Wait for administrator password"

counter=0
while [ $counter -lt 60 ]
do
    admin_password=`docker logs demo_anath-server_1 | awk '/password: / { print $2 }'`
    if [ -z "$admin_password" ]
    then
	printf "(%03d) Wait for admin password \r" $counter
	sleep 1
	counter=$(( counter + 1 ))
    else
	echo "Got admin password: $admin_password "
	break
    fi
done

if [ -z "$admin_password" ]
then
    echo "Password not seen after $counter tries. Aborting" >&2
    exit 1
fi

echo "$admin_password" > ANATH_ADMIN_PASSWORD
